#!/bin/sh

sudo apt-get update -y && apt-get install -y \
    apt-transport-https \
    ca-certificates \
    gnupg \
    ssh \
    sshpass \
    wget \
    curl \
    build-essential \
    libssl-dev \
    libffi-dev \
    && rm -rf /var/lib/apt/lists/*

# Install Docker
if ! [ -x "$(command -v docker)" ]; then
echo "Installing docker..."
sudo rm -f /etc/apt/keyrings/docker.gpg
sudo install -m 0755 -d /etc/apt/keyrings
sudo curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
sudo chmod a+r /etc/apt/keyrings/docker.gpg
echo \
  "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian \
  "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
  sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
sudo apt-get update -y
sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin -y
sudo usermod -aG docker $USER && newgrp docker
else
  echo "docker is already installed"
fi
echo "Installing docker is finish..."
sudo apt-get update -y
# sudo systemctl start docker.service
# Instal Kubectl
if ! [ -x "$(command -v kubectl)" ]; then
  echo "Installing kubectl..."
  curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
  chmod +x ./kubectl
  sudo mv kubectl /usr/local/bin/
else
  echo "kubectl is already installed"
fi
# Install minikube
if ! [ -x "$(command -v minikube)" ]; then
  echo "Installing minikube..."
  curl -Lo minikube https://storage.googleapis.com/minikube/releases/v1.30.1/minikube-linux-amd64
  chmod +x minikube
  sudo cp minikube /usr/local/bin/
else
  echo "minikube is already installed"
fi
sudo systemctl restart docker.service
echo "Starting minikube..."
minikube start
